# -*- coding: utf-8 -*-
"""
Figure 2a: show CBG-level POI visit-share redistribution.

This script directly reads the aggregated and anonymized
plotting data generated by pre_figure2a.py.

Required files
--------------
figure2a_original_visit_share.csv
figure2a_reassigned_visit_share.csv

No original absolute mobility-flow data are required.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import gridspec
from matplotlib.ticker import PercentFormatter
from matplotlib.colors import (
    PowerNorm,
    LinearSegmentedColormap
)


# =========================================================
# 0. Basic settings
# =========================================================

original_share_file = (
    'figure2a_original_visit_share.csv'
)

reassigned_share_file = (
    'figure2a_reassigned_visit_share.csv'
)


# Display settings
poi_num = 10
cbg_num = 10
save_fig = True
output_fig = 'figure2a.pdf'


# Heatmap color-enhancement settings.
# VISUAL_GAMMA < 1 compresses the high-share range and
# enlarges low-share differences.
# CMAP_MIN_CUT removes the nearly-white lower end of Blues,
# so low nonzero shares are more visible.
# ZERO_TOL controls which cells are treated as zero
# and drawn in pure white.
VISUAL_GAMMA = 0.45
CMAP_MIN_CUT = 0.18
CMAP_MAX_CUT = 1.00
ZERO_TOL = 1e-12


# =========================================================
# 1. Helper functions
# =========================================================

def normalize_rows_to_share(df):
    """
    Normalize each row to sum to 1.

    This converts absolute CBG-to-POI flows into within-CBG visit shares.
    If a row sum is 0, the normalized row is set to 0.
    """
    row_sums = df.sum(axis=1).replace(0, np.nan)
    share_df = df.div(row_sums, axis=0).fillna(0.0)
    return share_df


def truncate_colormap(base_cmap_name='Blues', min_cut=0.18, max_cut=1.00, n=256):
    """
    Remove the nearly-white part of a matplotlib colormap.

    This keeps zero and very small shares visually distinguishable while preserving
    the same blue color family.
    """
    base_cmap = plt.get_cmap(base_cmap_name)
    colors = base_cmap(np.linspace(min_cut, max_cut, n))
    return LinearSegmentedColormap.from_list(
        f'{base_cmap_name}_truncated_{min_cut:.2f}_{max_cut:.2f}',
        colors
    )


def make_visit_share_blue_cmap(n=256):
    """
    Sequential blue colormap:
    - darkest color: #4C78A8
    - middle color:  #C0D0E1
    - low values:    fade to near-white
    """
    colors = [
        "#FFFFFF",  # zero / near-zero neighborhood
        "#F4F7FA",
        "#E7EEF5",
        "#D5E1EC",
        "#C0D0E1",  # middle tone
        "#A9BDD4",
        "#89A8C8",
        "#6C90B9",
        "#4C78A8"   # darkest tone
    ]

    return LinearSegmentedColormap.from_list(
        "visit_share_soft_blue_balanced",
        colors,
        N=n
    )


def plot_cbg_visit_share_heatmaps(A_original, H_optimized, selected_cbgs, selected_pois,
                                  output_fig='figure2a_cbg_visit_share_deep_zero_white.pdf',
                                  save_fig=True,
                                  visual_gamma=0.45,
                                  cmap_min_cut=0.18,
                                  cmap_max_cut=1.00,
                                  zero_tol=1e-12):
    """
    Plot original and optimized CBG-level visit shares.

    Each row is normalized to 1, so colors represent the share of a CBG's
    visits allocated to each POI, not absolute visit counts.

    The heatmap intentionally uses PowerNorm(gamma < 1) plus a truncated Blues
    colormap. This visually strengthens low nonzero visit shares while keeping
    the same 0%--100% scale on the colorbar.

    Zero cells are masked and shown as pure white, so white means exactly
    no CBG-to-POI visits after row normalization, not merely a small share.
    """
    A_share = normalize_rows_to_share(A_original)
    H_share = normalize_rows_to_share(H_optimized)

    nrows = len(selected_cbgs)
    ncols = len(selected_pois)

    # Shared normalization: visit share is always between 0 and 1.
    # Use nonlinear color normalization to make low visit shares more visible.
    # With gamma < 1, small positive values receive stronger color contrast.
    norm = PowerNorm(gamma=visual_gamma, vmin=0, vmax=1)

    # Remove the almost-white lower end of Blues to deepen low-share cells.
    # Then explicitly set masked cells to pure white.
    # This way, zero cells are white, while low-but-positive cells are still blue.
    cmap = make_visit_share_blue_cmap()
    cmap = cmap.copy()

    # Use the same very light background tone as the new blue palette.
    # Masked zero cells will be drawn with this color.
    zero_color = "#F6F8FC"
    cmap.set_bad(color=zero_color)

    # Mask exact or near-zero shares. These cells will be drawn as pure white.
    A_share_plot = np.ma.masked_where(A_share.values <= zero_tol, A_share.values)
    H_share_plot = np.ma.masked_where(H_share.values <= zero_tol, H_share.values)

    # Two heatmap panels only. The colorbar is placed manually relative to ax2.
    # This makes the colorbar height and the gap between the colorbar and heatmap easier to control.
    axis_aspect = ncols / nrows
    width_ratios = [axis_aspect, axis_aspect]

    fig = plt.figure(figsize=(16, 8), dpi=300)
    gs = gridspec.GridSpec(
        nrows=1,
        ncols=2,
        width_ratios=width_ratios,
        wspace=0.10   # 控制两个热图之间的距离；越小越近
    )

    ax1 = fig.add_subplot(gs[0, 0])
    ax2 = fig.add_subplot(gs[0, 1])

    im1 = ax1.imshow(
        A_share_plot,
        cmap=cmap,
        norm=norm,
        interpolation='nearest',
        origin='upper',
        aspect='equal'
    )
    im2 = ax2.imshow(
        H_share_plot,
        cmap=cmap,
        norm=norm,
        interpolation='nearest',
        origin='upper',
        aspect='equal'
    )

    # -----------------------------------------------------
    # Manual colorbar placement.
    # Main controls:
    #   cbar_gap          : distance from the optimized heatmap to the colorbar
    #   cbar_width        : width of the colorbar
    #   cbar_height_ratio : height relative to the optimized heatmap
    #   cbar_y_shift      : vertical shift; positive moves upward, negative moves downward
    # -----------------------------------------------------
    pos2 = ax2.get_position()

    cbar_gap = 0.006          # 越小，cbar 离右侧热图越近；可试 0.003, 0.006, 0.012
    cbar_width = 0.014        # cbar 宽度；可试 0.010--0.020
    cbar_height_ratio = 0.97  # cbar 高度；1.00 与热图等高，0.85 为 85%
    cbar_y_shift = 0.03      # 向上移动用正数，如 0.02；向下移动用负数

    cbar_height = pos2.height * cbar_height_ratio
    cbar_x = pos2.x1 + cbar_gap
    cbar_y = pos2.y0 + (pos2.height - cbar_height) / 2 + cbar_y_shift

    cax = fig.add_axes([cbar_x, cbar_y, cbar_width, cbar_height])

    poi_labels = [f'POI{i + 1}' for i in range(ncols)]
    cbg_labels = [f'CBG{i + 1}' for i in range(nrows)]

    for ax in (ax1, ax2):
        ax.set_xticks(np.arange(ncols))
        ax.set_xticklabels(poi_labels, rotation=0, ha='center', fontsize=14)
        ax.set_yticks(np.arange(nrows))
        ax.set_yticklabels(cbg_labels, fontsize=14)

        # Add light grid lines to make row-wise redistribution clearer.
        ax.set_xticks(np.arange(-0.5, ncols, 1), minor=True)
        ax.set_yticks(np.arange(-0.5, nrows, 1), minor=True)
        ax.grid(which='minor', color='white', linestyle='-', linewidth=0.6)
        ax.tick_params(which='minor', bottom=False, left=False)

    # Only keep y labels on the left panel.
    ax2.tick_params(left=False, labelleft=False)

    ax1.set_title('Original Visit Share', pad=8, fontsize=14.5)
    ax2.set_title('Reassigned Visit Share', pad=8, fontsize=14.5)

    cb = fig.colorbar(im2, cax=cax, orientation='vertical')
    cb.set_label('Within-CBG Visit Share', rotation=90, labelpad=6, fontsize=12)
    cb.ax.yaxis.set_major_formatter(PercentFormatter(xmax=1.0))
    
    # 调整刻度数字大小
    cb.ax.tick_params(axis='y', labelsize=12)

    # Avoid tight_layout here because the colorbar is manually positioned.
    # If you need more left/right margin, adjust these values instead.
    plt.subplots_adjust(left=0.08, right=0.90, bottom=0.16, top=0.88)

    plt.savefig('figure2a.pdf',
                format='pdf',
                dpi=300,
                bbox_inches='tight',
                transparent=False,
                backend='pdf')

    plt.show()

    return A_share, H_share


# =========================================================
# 2. Load Figure 2a plotting data
# =========================================================

A_original = pd.read_csv(
    original_share_file,
    index_col=0
)

H_optimized = pd.read_csv(
    reassigned_share_file,
    index_col=0
)


# Use dimensions and ordering stored in the plotting files.
selected_cbgs = A_original.index.tolist()
selected_pois = A_original.columns.tolist()


# =========================================================
# 3. Basic consistency checks
# =========================================================

if A_original.shape != H_optimized.shape:
    raise ValueError(
        "Original and reassigned plotting matrices "
        "must have the same dimensions."
    )


if A_original.index.tolist() != H_optimized.index.tolist():
    raise ValueError(
        "CBG ordering differs between the two plotting files."
    )


if A_original.columns.tolist() != H_optimized.columns.tolist():
    raise ValueError(
        "POI ordering differs between the two plotting files."
    )


print(
    "Original plotting-data row sums:"
)

print(
    A_original.sum(axis=1)
)


print(
    "\nReassigned plotting-data row sums:"
)

print(
    H_optimized.sum(axis=1)
)


# =========================================================
# 4. Plot Figure 2a
# =========================================================

A_share, H_share = plot_cbg_visit_share_heatmaps(
    A_original=A_original,
    H_optimized=H_optimized,
    selected_cbgs=selected_cbgs,
    selected_pois=selected_pois,
    output_fig=output_fig,
    save_fig=save_fig,
    visual_gamma=VISUAL_GAMMA,
    cmap_min_cut=CMAP_MIN_CUT,
    cmap_max_cut=CMAP_MAX_CUT,
    zero_tol=ZERO_TOL
)