# -*- coding: utf-8 -*-
"""
Fig. 4b:
Observed baseline flow F versus
behaviorally informed reference flow R.

Required public inputs:

    figure4b_baseline_flow.csv
    figure4b_reference_flow.csv

    geo_data/
        tl_2021_boston_msa_bg/
            tl_2021_boston_msa_bg.shp

The two flow matrices are generated by:

    pre_figure4b.py

All scripts are intended to be run from the
repository root directory.
"""

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt


# ============================================================
# Basic settings
# ============================================================

baseline_path = (
    'figure4b_baseline_flow.csv'
)

reference_path = (
    'figure4b_reference_flow.csv'
)

shapefile_path = (
    'geo_data/'
    'tl_2021_boston_msa_bg/'
    'tl_2021_boston_msa_bg.shp'
)


# ============================================================
# Check files
# ============================================================

for path in [
    baseline_path,
    reference_path,
    shapefile_path,
]:
    if not os.path.exists(path):

        raise FileNotFoundError(
            f'Cannot find required file:\n'
            f'{path}'
        )


# ============================================================
# Load public Fig.4b data
# ============================================================

baseline = pd.read_csv(
    baseline_path,
    index_col=0
)

R = pd.read_csv(
    reference_path,
    index_col=0
)


# ============================================================
# Load shapefile
#
# Retained exactly for the same purpose as in the
# original Fig.4b code: determining GEOID pad length.
# ============================================================

boston_msa_cbg = gpd.read_file(
    shapefile_path
)

boston_msa_cbg['GEOID'] = (
    boston_msa_cbg['GEOID']
    .astype(str)
)

pad_len = int(
    boston_msa_cbg['GEOID']
    .str.len()
    .max()
)


# ============================================================
# Standardize baseline index / columns
# ============================================================

baseline.index = [
    str(x).zfill(pad_len)
    for x in baseline.index
]

baseline.columns = [
    str(x)
    for x in baseline.columns
]


# ============================================================
# Align public R matrix to baseline
# ============================================================

def align_H_to_baseline(
    H_df,
    baseline_df,
    pad_len
):
    """
    Align H_df to baseline_df.

    baseline.index contains zero-padded GEOID strings.
    POI IDs are converted only to strings and are not padded.
    """

    H = H_df.copy()

    H.index = H.index.map(
        lambda x:
        str(x)
    )

    H.columns = H.columns.map(
        lambda x:
        str(x)
    )


    # --------------------------------------------------------
    # Direct string matching
    # --------------------------------------------------------

    H_try = H.reindex(
        index=baseline_df.index,
        columns=baseline_df.columns
    )

    if H_try.notna().values.any():

        H_aligned = (
            H_try.fillna(0)
        )

        print(
            'align_H_to_baseline: '
            'direct string match found, '
            f'nonzero sum = '
            f'{H_aligned.values.sum():.4f}'
        )

        return H_aligned


    # --------------------------------------------------------
    # If pandas removed GEOID leading zeros,
    # restore them using the shapefile-derived pad length.
    # --------------------------------------------------------

    H.index = H.index.map(
        lambda x:
        str(x).zfill(pad_len)
    )

    H_try = H.reindex(
        index=baseline_df.index,
        columns=baseline_df.columns
    )

    if H_try.notna().values.any():

        H_aligned = (
            H_try.fillna(0)
        )

        print(
            'align_H_to_baseline: '
            'zero-padded string match found, '
            f'nonzero sum = '
            f'{H_aligned.values.sum():.4f}'
        )

        return H_aligned


    raise ValueError(
        'Cannot align '
        'figure4b_reference_flow.csv '
        'to figure4b_baseline_flow.csv.'
    )


# ============================================================
# Prepare plotting matrices
# ============================================================

R_aligned = align_H_to_baseline(
    R,
    baseline,
    pad_len
)

baseline_df = baseline.copy()


# ============================================================
# Original plotting logic starts here
# ============================================================

# 选择用于绘图的节点顺序（用 baseline 的总流量排序以保证一致性）
top_cbgs = (
    baseline_df
    .sum(axis=1)
    .sort_values(
        ascending=False
    )
    .index
    .tolist()
)

top_pois = (
    baseline_df
    .sum(axis=0)
    .sort_values(
        ascending=False
    )
    .index
    .tolist()
)

cbgs_all = [
    str(x)
    for x in top_cbgs
]

pois_all = [
    str(x)
    for x in top_pois
]


# 仅保留同时存在于 baseline 与 R 矩阵的节点
# （应该都存在，但稳健处理）
def get_present_lists(
    df_ref,
    df_other
):
    idx = [
        str(x)
        for x in df_ref.index
    ]

    cols = [
        str(x)
        for x in df_ref.columns
    ]

    idx_present = [
        c
        for c in idx
        if (
            c in df_ref.index
            and
            c in df_other.index
        )
    ]

    cols_present = [
        p
        for p in cols
        if (
            p in df_ref.columns
            and
            p in df_other.columns
        )
    ]

    return (
        idx_present,
        cols_present
    )


# 因为我们对两表对齐，直接用 baseline 的索引/列即可
cbgs_present = [
    str(x)
    for x in baseline_df.index
]

pois_present = [
    str(x)
    for x in baseline_df.columns
]


# 位置布置（与之前的风格一致：CBG 在上，POI 在下）
n_cbgs = len(
    cbgs_present
)

n_pois = len(
    pois_present
)

x_cbgs = (
    np.linspace(
        0.03,
        0.97,
        n_cbgs
    )
    if n_cbgs > 0
    else np.array([])
)

x_pois = (
    np.linspace(
        0.03,
        0.97,
        n_pois
    )
    if n_pois > 0
    else np.array([])
)

y_cbgs = (
    np.ones_like(
        x_cbgs
    )
    * 1.0
)

y_pois = (
    np.zeros_like(
        x_pois
    )
    * 0.0
)


# 辅助：从 DataFrame 构建边列表 (i, j, value)
# —— 与你原实现保持一致（兼容单列/单行）
def build_edges_from_df(
    df,
    cbgs_present,
    pois_present
):

    df_str = df.copy()

    df_str.index = (
        df_str.index.map(
            lambda x:
            str(x)
        )
    )

    df_str.columns = (
        df_str.columns.map(
            lambda x:
            str(x)
        )
    )

    edges = []

    for i, cbg in enumerate(
        cbgs_present
    ):

        row = None

        try:

            row = df_str.loc[
                cbg,
                pois_present
            ]

        except Exception:

            try:

                if len(
                    pois_present
                ) > 0:

                    row = df_str.loc[
                        cbg,
                        pois_present[0]
                    ]

            except Exception:

                row = None

        if row is None:

            continue

        row_vals = np.atleast_1d(
            np.array(
                row,
                dtype=float
            )
        )

        for j, v in enumerate(
            row_vals
        ):

            if np.isnan(v):

                continue

            if v > 0:

                edges.append(
                    (
                        i,
                        j,
                        float(v)
                    )
                )

    return edges


# 线宽映射（直接复用）
def map_widths(
    edges,
    min_lw=0.1,
    max_lw=5.0
):

    if len(edges) == 0:

        return np.array([])

    vals = np.array(
        [
            e[2]
            for e in edges
        ],
        dtype=float
    )

    vmin = vals.min()
    vmax = vals.max()

    if vmax == vmin:

        return np.full_like(
            vals,
            (
                min_lw
                +
                max_lw
            )
            / 2.0,
            dtype=float
        )

    return (
        min_lw
        +
        (
            vals
            -
            vmin
        )
        /
        (
            vmax
            -
            vmin
        )
        *
        (
            max_lw
            -
            min_lw
        )
    )


# 贝塞尔画边函数（跟你原始实现保持一致）
def draw_edges_to_ax(
    ax,
    edges,
    widths,
    x_cbgs,
    y_cbgs,
    x_pois,
    y_pois,
    edge_alpha=0.7,
    color='#87CEFA'
):

    if len(edges) == 0:

        ax.text(
            0.5,
            0.5,
            'No positive flows to plot',
            ha='center',
            va='center',
            fontsize=12,
            color=color
        )

        return

    vals = np.array(
        [
            e[2]
            for e in edges
        ],
        dtype=float
    )

    order = np.argsort(
        vals
    )

    t = np.linspace(
        0.0,
        1.0,
        120
    )

    for idx in order:

        i, j, v = edges[idx]

        lw = float(
            widths[idx]
        )

        if (
            i >= len(x_cbgs)
            or
            j >= len(x_pois)
        ):

            continue

        x0 = float(
            x_cbgs[i]
        )

        y0 = float(
            y_cbgs[i]
        )

        x1 = float(
            x_pois[j]
        )

        y1 = float(
            y_pois[j]
        )

        xm = (
            x0
            +
            x1
        ) / 2.0

        dx = (
            x1
            -
            x0
        )

        bend = (
            0.15
            +
            0.35
            *
            abs(dx)
        )

        ym = (
            0.35
            +
            bend
            *
            0.6
        )

        P0 = np.array(
            [
                x0,
                y0
            ]
        )

        P1 = np.array(
            [
                xm,
                ym
            ]
        )

        P2 = np.array(
            [
                x1,
                y1
            ]
        )

        curve = (
            (
                (1 - t) ** 2
            )[:, None]
            *
            P0
            +
            2
            *
            (
                (1 - t)
                *
                t
            )[:, None]
            *
            P1
            +
            (
                t ** 2
            )[:, None]
            *
            P2
        )

        ax.plot(
            curve[:, 0],
            curve[:, 1],
            linewidth=lw,
            color=color,
            alpha=edge_alpha,
            solid_capstyle='round',
            zorder=1
        )


# 替换：更短的 draw_edges_to_ax
# （曲线两端裁掉 t_margin）
def draw_edges_to_ax(
    ax,
    edges,
    widths,
    x_cbgs,
    y_cbgs,
    x_pois,
    y_pois,
    edge_alpha=0.7,
    color='#87CEFA'
):

    if len(edges) == 0:

        ax.text(
            0.5,
            0.5,
            'No positive flows to plot',
            ha='center',
            va='center',
            fontsize=12,
            color=color
        )

        return

    vals = np.array(
        [
            e[2]
            for e in edges
        ],
        dtype=float
    )

    order = np.argsort(
        vals
    )


    # 控制端点留白的比例
    # （0.0-0.45，越大端点离节点越远）
    t_margin = 0.01

    t_margin = min(
        max(
            0.0,
            t_margin
        ),
        0.1
    )

    t = np.linspace(
        t_margin,
        1.0 - t_margin,
        120
    )


    for idx in order:

        i, j, v = edges[idx]

        lw = float(
            widths[idx]
        )


        # 若索引越界则跳过（稳健）
        if (
            i >= len(x_cbgs)
            or
            j >= len(x_pois)
        ):

            continue


        x0 = float(
            x_cbgs[i]
        )

        y0 = float(
            y_cbgs[i]
        )

        x1 = float(
            x_pois[j]
        )

        y1 = float(
            y_pois[j]
        )


        # 中间控制点（保持你原来的弯曲策略）
        xm = (
            x0
            +
            x1
        ) / 2.0

        dx = (
            x1
            -
            x0
        )

        bend = (
            0.15
            +
            0.35
            *
            abs(dx)
        )

        ym = (
            0.35
            +
            bend
            *
            0.6
        )


        P0 = np.array(
            [
                x0,
                y0
            ]
        )

        P1 = np.array(
            [
                xm,
                ym
            ]
        )

        P2 = np.array(
            [
                x1,
                y1
            ]
        )


        # 计算裁切后的二次贝塞尔曲线
        curve = (
            (
                (1 - t) ** 2
            )[:, None]
            *
            P0
            +
            2
            *
            (
                (1 - t)
                *
                t
            )[:, None]
            *
            P1
            +
            (
                t ** 2
            )[:, None]
            *
            P2
        )


        # 绘制，保证边在节点下面
        ax.plot(
            curve[:, 0],
            curve[:, 1],
            linewidth=lw,
            color=color,
            alpha=edge_alpha,
            solid_capstyle='round',
            zorder=2
        )


# 控制绘制密度
max_edges = 40000


def cap_edges(
    edges
):

    if len(edges) == 0:

        return edges

    edges = sorted(
        edges,
        key=lambda x:
        x[2],
        reverse=True
    )

    return edges[
        :
        min(
            len(edges),
            max_edges
        )
    ]


# ============================================================
# Build edges
# ============================================================

edges_baseline = build_edges_from_df(
    baseline_df,
    cbgs_present,
    pois_present
)

edges_R = build_edges_from_df(
    R_aligned,
    cbgs_present,
    pois_present
)


edges_baseline = cap_edges(
    edges_baseline
)

edges_R = cap_edges(
    edges_R
)


# ============================================================
# Calculate edge widths
# ============================================================

widths_baseline = map_widths(
    edges_baseline
)

widths_R = map_widths(
    edges_R
)


# ============================================================
# Plot
# ============================================================

fig, axes = plt.subplots(
    1,
    2,
    figsize=(10, 5),
    dpi=300
)

ax0, ax1 = axes


COLOR = '#3498db'


# ============================================================
# Baseline
# ============================================================

ax0.set_title(
    'Observed Baseline Flow F (CBG → POI)',
    fontsize=14,
    pad=1
)

ax0.axis(
    'off'
)

draw_edges_to_ax(
    ax0,
    edges_baseline,
    widths_baseline,
    x_cbgs,
    y_cbgs,
    x_pois,
    y_pois,
    edge_alpha=0.7,
    color=COLOR
)

ax0.scatter(
    x_cbgs,
    y_cbgs,
    s=10,
    marker='o',
    color='#3498db',
    alpha=0.95,
    zorder=5,
    edgecolors='none'
)

# ax0.scatter(
#     x_pois,
#     y_pois,
#     s=20,
#     marker='o',
#     color='#e74c3f',
#     alpha=0.95,
#     zorder=5,
#     edgecolors='none'
# )

ax0.scatter(
    x_pois,
    y_pois,
    s=20,
    marker='o',
    color='#7c5bb8',
    alpha=0.95,
    zorder=5,
    edgecolors='none'
)


# ============================================================
# R
# ============================================================

ax1.set_title(
    'Behaviorally Informed Reference Flow R (CBG → POI)',
    fontsize=14,
    pad=1
)

ax1.axis(
    'off'
)

draw_edges_to_ax(
    ax1,
    edges_R,
    widths_R,
    x_cbgs,
    y_cbgs,
    x_pois,
    y_pois,
    edge_alpha=0.7,
    color=COLOR
)

ax1.scatter(
    x_cbgs,
    y_cbgs,
    s=10,
    marker='o',
    color='#3498db',
    alpha=0.95,
    zorder=5,
    edgecolors='none'
)

# ax1.scatter(
#     x_pois,
#     y_pois,
#     s=20,
#     marker='o',
#     color='#e74c3f',
#     alpha=0.95,
#     zorder=5,
#     edgecolors='none'
# )

ax1.scatter(
    x_pois,
    y_pois,
    s=20,
    marker='o',
    color='#7c5bb8',
    alpha=0.95,
    zorder=5,
    edgecolors='none'
)


# ============================================================
# Save
# ============================================================

plt.tight_layout()

plt.savefig(
    'figure4b.pdf',
    format='pdf',
    dpi=300,
    bbox_inches='tight',
    transparent=False,
    backend='pdf'
)

plt.show()