# -*- coding: utf-8 -*-
"""
Fig.3a public plotting code.

This version plots 101 values:
    b = 0%, 1%, 2%, ..., 100%

All three panels:
    left y-axis  = raw value
    right y-axis = percentage change from observed baseline

Panels:
    1) Left:  SPSE
       Right: SPSE change from baseline (%)

    2) Left:  Total travel distance
       Right: Total distance change from baseline (%)

    3) Left:  Flow-weighted exposure
       Right: Flow-weighted exposure change from baseline (%)

Required input:
    k_matrices_boston_family_budget.csv
    figure3a_baseline.csv

Required columns in k_matrices_boston_family_budget.csv:
    budget
    f_last
    distances_last
    social_last
    social_weight_last

Required columns in figure3a_baseline.csv:
    baseline_total_flow
    baseline_spse
    baseline_flow_weighted_exposure
    baseline_total_distance
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# User parameters
# ============================================================

city = "boston"
category = "Other Individual and Family Services"
cat_dir = f"matrices_A_D_S_Distribution/{category.replace(' ', '_')}"

CSV_PATH = "k_matrices_boston_family_budget.csv"
BASELINE_PATH = "figure3a_baseline.csv"

OUT_PDF = "figure3a_101_values_dual_axis.pdf"
OUT_PNG = "figure3a_101_values_dual_axis.png"
OUT_CSV = "figure3a_101_values_dual_axis.csv"

EPS = 1e-10

income_levels = [
    "low_income_pct",
    "lower_middle_income_pct",
    "upper_middle_income_pct",
    "high_income_pct"
]


# ============================================================
# Helper functions
# ============================================================

def normalize_key(x):
    if pd.isna(x):
        return ""
    s = str(x).strip()
    if s.endswith(".0") and s[:-2].isdigit():
        s = s[:-2]
    return s


def normalize_df_index_columns(df):
    df = df.copy()
    df.index = [
        normalize_key(x)
        for x in df.index
    ]
    df.columns = [
        normalize_key(x)
        for x in df.columns
    ]
    return df


def sparse_marker(arr, step=5):
    """Return an array with values only every `step` points."""
    arr = np.asarray(
        arr,
        dtype=float
    )

    out = np.full(
        arr.shape,
        np.nan,
        dtype=float
    )

    out[::step] = arr[::step]

    return out


def make_secondary_pct_axis(
    ax,
    baseline_value,
    ylabel
):
    """
    Add a secondary y-axis showing percentage change from baseline.

    Left axis uses raw value.

    Right axis uses:
        (value - baseline) / baseline * 100
    """

    if abs(baseline_value) <= EPS:
        raise ValueError(
            "Baseline value is zero or too small "
            "for percentage-axis conversion."
        )

    def value_to_pct(y):
        return (
            (np.asarray(y) - baseline_value)
            / baseline_value
            * 100.0
        )

    def pct_to_value(p):
        return (
            baseline_value
            * (1.0 + np.asarray(p) / 100.0)
        )

    secax = ax.secondary_yaxis(
        "right",
        functions=(
            value_to_pct,
            pct_to_value
        )
    )

    secax.set_ylabel(
        ylabel,
        labelpad=2
    )

    secax.tick_params(
        axis="y",
        which="major",
        labelsize=9,
        width=0.6,
        direction="in"
    )

    return secax


# ============================================================
# Load budget results
# ============================================================

if not os.path.isfile(CSV_PATH):
    raise FileNotFoundError(
        f"CSV file not found: {CSV_PATH}"
    )

budget_df = pd.read_csv(
    CSV_PATH
)

budget_df = (
    budget_df
    .sort_values("budget")
    .reset_index(drop=True)
)

required_cols = [
    "budget",
    "f_last",
    "distances_last",
    "social_last",
    "social_weight_last"
]

missing_cols = [
    c for c in required_cols
    if c not in budget_df.columns
]

if missing_cols:
    raise ValueError(
        f"Missing required columns in "
        f"{CSV_PATH}: {missing_cols}\n"
        f"Available columns: "
        f"{list(budget_df.columns)}"
    )

print(
    "[LOAD] budget CSV:",
    CSV_PATH
)

print(
    "[LOAD] n budget rows:",
    len(budget_df)
)

print(
    "[LOAD] columns:",
    list(budget_df.columns)
)


# ============================================================
# Load original baseline generated by pre_figure3a.py
# ============================================================

if not os.path.isfile(BASELINE_PATH):
    raise FileNotFoundError(
        f"Baseline CSV file not found: "
        f"{BASELINE_PATH}"
    )

baseline_df = pd.read_csv(
    BASELINE_PATH
)

required_baseline_cols = [
    "baseline_total_flow",
    "baseline_spse",
    "baseline_flow_weighted_exposure",
    "baseline_total_distance"
]

missing_baseline_cols = [
    c for c in required_baseline_cols
    if c not in baseline_df.columns
]

if missing_baseline_cols:
    raise ValueError(
        f"Missing required columns in "
        f"{BASELINE_PATH}: "
        f"{missing_baseline_cols}\n"
        f"Available columns: "
        f"{list(baseline_df.columns)}"
    )

if len(baseline_df) != 1:
    raise ValueError(
        f"{BASELINE_PATH} should contain "
        f"exactly one baseline row."
    )


baseline_spse = float(
    baseline_df.loc[
        0,
        "baseline_spse"
    ]
)

baseline_flow_weighted_exposure = float(
    baseline_df.loc[
        0,
        "baseline_flow_weighted_exposure"
    ]
)

baseline_total_distance = float(
    baseline_df.loc[
        0,
        "baseline_total_distance"
    ]
)

baseline_total_flow = float(
    baseline_df.loc[
        0,
        "baseline_total_flow"
    ]
)


if "n_cbgs" in baseline_df.columns:
    n_cbgs = int(
        baseline_df.loc[
            0,
            "n_cbgs"
        ]
    )
else:
    n_cbgs = np.nan


if "n_pois" in baseline_df.columns:
    n_pois = int(
        baseline_df.loc[
            0,
            "n_pois"
        ]
    )
else:
    n_pois = np.nan


print(
    "\n========== ORIGINAL BASELINE =========="
)

if not pd.isna(n_cbgs):
    print(
        f"n_CBGs: {n_cbgs}"
    )

if not pd.isna(n_pois):
    print(
        f"n_POIs: {n_pois}"
    )

print(
    f"baseline total flow: "
    f"{baseline_total_flow:.6f}"
)

print(
    f"baseline SPSE: "
    f"{baseline_spse:.6f}"
)

print(
    f"baseline flow-weighted exposure: "
    f"{baseline_flow_weighted_exposure:.6f}"
)

print(
    f"baseline total travel distance: "
    f"{baseline_total_distance:.6f}"
)


# ============================================================
# Build plotting table: 101 values
# ============================================================

budget_part = budget_df[[
    "budget",
    "f_last",
    "distances_last",
    "social_last",
    "social_weight_last"
]].copy()


budget_part = budget_part.rename(
    columns={
        "f_last":
            "objective",

        "distances_last":
            "total_distance",

        "social_last":
            "spse",

        "social_weight_last":
            "flow_weighted_exposure"
    }
)


budget_part["budget_pct"] = (
    budget_part["budget"]
    .astype(float)
    * 100.0
)


# Add b = 0 observed baseline row.
baseline_row = pd.DataFrame([{
    "budget": 0.0,
    "budget_pct": 0.0,
    "objective": np.nan,
    "total_distance":
        baseline_total_distance,
    "spse":
        baseline_spse,
    "flow_weighted_exposure":
        baseline_flow_weighted_exposure
}])


fig_df = pd.concat(
    [
        baseline_row,
        budget_part
    ],
    ignore_index=True
)

fig_df = (
    fig_df
    .sort_values("budget_pct")
    .reset_index(drop=True)
)


# Right-axis percentage changes.
fig_df["spse_change_pct"] = (
    (
        fig_df["spse"]
        - baseline_spse
    )
    / baseline_spse
    * 100.0
)


fig_df["total_distance_change_pct"] = (
    (
        fig_df["total_distance"]
        - baseline_total_distance
    )
    / baseline_total_distance
    * 100.0
)


fig_df[
    "flow_weighted_exposure_change_pct"
] = (
    (
        fig_df["flow_weighted_exposure"]
        - baseline_flow_weighted_exposure
    )
    / baseline_flow_weighted_exposure
    * 100.0
)


if len(fig_df) != 101:
    print(
        f"[WARN] Expected 101 rows, "
        f"but got {len(fig_df)} rows."
    )


# ============================================================
# Print Figure 3a key values
# ============================================================

key_budgets = [
    0.01,
    0.05,
    0.10,
    0.15,
    0.20,
    0.30,
    0.40,
    0.60,
    0.80,
    1.00
]


key_rows = []


for b in key_budgets:

    diff = (
        fig_df["budget"]
        .astype(float)
        - b
    ).abs()

    idx = diff.idxmin()

    if diff.loc[idx] > 1e-8:

        print(
            f"[WARN] budget={b:.2f} "
            f"was not found exactly; "
            f"using nearest budget="
            f"{fig_df.loc[idx, 'budget']:.6f}"
        )

    key_rows.append(
        fig_df.loc[idx]
    )


key_values_df = pd.DataFrame(
    key_rows
)[[
    "budget",
    "objective",
    "total_distance",
    "spse",
    "flow_weighted_exposure"
]].copy()


key_values_df = (
    key_values_df.rename(
        columns={
            "total_distance":
                "distance",

            "spse":
                "social_exposure"
        }
    )
)


print(
    "\n=== Figure 3a key values ==="
)


print(
    key_values_df.to_string(
        index=False,
        formatters={
            "budget":
                lambda x: f"{x:.2f}",

            "objective":
                lambda x: f"{x:.6f}",

            "distance":
                lambda x: f"{x:.6f}",

            "social_exposure":
                lambda x: f"{x:.6f}",

            "flow_weighted_exposure":
                lambda x: f"{x:.6f}",
        }
    )
)


# ============================================================
# Extract arrays
# ============================================================

x_budget = (
    fig_df["budget_pct"]
    .values
    .astype(float)
)


spse_value = (
    fig_df["spse"]
    .values
    .astype(float)
)


total_distance_value = (
    fig_df["total_distance"]
    .values
    .astype(float)
)


flow_weighted_exposure_value = (
    fig_df["flow_weighted_exposure"]
    .values
    .astype(float)
)


# ============================================================
# Plot
# ============================================================

color_static = "#4C78A8"
color_dynamic = "#8E5EA2"

colors = [
    "#3498db",
    "#7c5bb8",
    "#e74c3c"
]   # blue / purple / red

colors = [
    "#4C78A8",
    "#8E5EA2",
    "#C76B6B"
]   # blue / purple / red

markers = [
    "o",
    "s",
    "^"
]


plt.rcParams.update({
    "font.size": 10,
    "axes.linewidth": 0.8,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "grid.linewidth": 0.4,
    "grid.alpha": 0.5,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})


fig, axs = plt.subplots(
    1,
    3,
    figsize=(15, 5),
    dpi=300
)


# ------------------------------------------------------------
# Panel 2: Total travel distance
# Left axis: total travel distance
# Right axis: distance change from baseline (%)
# ------------------------------------------------------------

ax = axs[0]


ax.plot(
    x_budget,
    total_distance_value,
    color=colors[0],
    linewidth=3
)


ax.plot(
    x_budget,
    sparse_marker(
        total_distance_value
    ),
    color=colors[0],
    marker=markers[0],
    markersize=8,
    markeredgewidth=1,
    markerfacecolor="w",
    linestyle="None",
    clip_on=False
)


ax.set_xlabel(
    "Reallocation budget, $\gamma$",
    labelpad=2
)

ax.set_ylabel(
    "Total travel distance (km)",
    labelpad=2
)

ax.set_title(
    "Travel cost"
)

ax.grid(
    True,
    linestyle="--",
    alpha=0.4
)

ax.set_xlim(
    x_budget.min(),
    x_budget.max()
)


make_secondary_pct_axis(
    ax,
    baseline_total_distance,
    "Distance change from baseline (%)"
)


# ------------------------------------------------------------
# Panel 2: Structural potential social exposure
# Left axis: SPSE
# Right axis: SPSE change from baseline (%)
# ------------------------------------------------------------

ax = axs[1]


ax.plot(
    x_budget,
    spse_value,
    color=colors[1],
    linewidth=3
)


ax.plot(
    x_budget,
    sparse_marker(
        spse_value
    ),
    color=colors[1],
    marker=markers[1],
    markersize=8,
    markeredgewidth=1,
    markerfacecolor="w",
    linestyle="None",
    clip_on=False
)


ax.set_xlabel(
    "Reallocation budget, $\gamma$",
    labelpad=2
)

ax.set_ylabel(
    "Structural potential social exposure",
    labelpad=2
)

ax.set_title(
    "Structural exposure"
)

ax.grid(
    True,
    linestyle="--",
    alpha=0.4
)

ax.set_xlim(
    x_budget.min(),
    x_budget.max()
)


make_secondary_pct_axis(
    ax,
    baseline_spse,
    "SPSE change from baseline (%)"
)


# ------------------------------------------------------------
# Panel 3: Flow-weighted exposure
# Left axis: flow-weighted exposure
# Right axis: flow-weighted exposure change from baseline (%)
# ------------------------------------------------------------

ax = axs[2]


ax.plot(
    x_budget,
    flow_weighted_exposure_value,
    color=colors[2],
    linewidth=3
)


ax.plot(
    x_budget,
    sparse_marker(
        flow_weighted_exposure_value
    ),
    color=colors[2],
    marker=markers[2],
    markersize=8,
    markeredgewidth=1,
    markerfacecolor="w",
    linestyle="None",
    clip_on=False
)


ax.set_xlabel(
    "Reallocation budget, $\gamma$",
    labelpad=2
)

ax.set_ylabel(
    "Flow-weighted exposure",
    labelpad=2
)

ax.set_title(
    "Flow-weighted exposure"
)

ax.grid(
    True,
    linestyle="--",
    alpha=0.4
)

ax.set_xlim(
    x_budget.min(),
    x_budget.max()
)


make_secondary_pct_axis(
    ax,
    baseline_flow_weighted_exposure,
    "Flow-weighted exposure change (%)"
)


# ------------------------------------------------------------
# Common formatting
# ------------------------------------------------------------

for ax in axs:

    ax.tick_params(
        axis="both",
        which="major",
        labelsize=9
    )

    ax.set_xticks([
        0,
        20,
        40,
        60,
        80,
        100
    ])

    ax.set_xticklabels([
        "0",
        "20",
        "40",
        "60",
        "80",
        "100"
    ])


plt.tight_layout()


plt.savefig(
    "figure3a.pdf",
    format="pdf",
    dpi=300,
    bbox_inches="tight",
    transparent=False,
    backend="pdf"
)


plt.show()


# ============================================================
# 输出 Fig.3a 正文对应的关键数值
# ============================================================

def get_budget_row(budget):

    idx = (
        fig_df["budget"]
        .astype(float)
        - budget
    ).abs().idxmin()

    return fig_df.loc[idx]


row_001 = get_budget_row(
    0.01
)

row_020 = get_budget_row(
    0.20
)


positive_df = (
    fig_df[
        fig_df["budget"] > 0
    ]
    .copy()
)


max_spse_row = (
    positive_df.loc[
        positive_df["spse"].idxmax()
    ]
)


last_spse = (
    spse_value[-1]
)


spse_recovered_pct = (
    (
        row_020["spse"]
        - row_001["spse"]
    )
    /
    (
        last_spse
        - row_001["spse"]
    )
    * 100
)


large_budget_df = (
    fig_df[
        fig_df["budget"] >= 0.20
    ]
)


plateau_df = (
    fig_df[
        fig_df["budget"] >= 0.40
    ]
)


print(
    "\n========== Fig.3a manuscript values =========="
)


print(
    f"Baseline: "
    f"SPSE={baseline_spse:.4f}, "
    f"flow-weighted exposure="
    f"{baseline_flow_weighted_exposure:.6f}, "
    f"distance="
    f"{baseline_total_distance:.2f} km"
)


print(
    f"gamma=0.01: "
    f"SPSE={row_001['spse']:.4f} "
    f"({row_001['spse_change_pct']:+.2f}%), "
    f"flow-weighted exposure="
    f"{row_001['flow_weighted_exposure']:.6f} "
    f"({row_001['flow_weighted_exposure_change_pct']:+.2f}%), "
    f"distance="
    f"{row_001['total_distance']:.2f} km "
    f"({row_001['total_distance_change_pct']:+.2f}%)"
)


print(
    f"gamma=0.20: "
    f"SPSE={row_020['spse']:.4f} "
    f"({row_020['spse_change_pct']:+.2f}%), "
    f"flow-weighted exposure="
    f"{row_020['flow_weighted_exposure']:.6f} "
    f"({row_020['flow_weighted_exposure_change_pct']:+.2f}%), "
    f"distance="
    f"{row_020['total_distance']:.2f} km "
    f"({row_020['total_distance_change_pct']:+.2f}%)"
)


print(
    f"Share of the gamma=0.01-to-last "
    f"SPSE gain recovered by gamma=0.20: "
    f"{spse_recovered_pct:.2f}%"
)


print(
    f"Flow-weighted exposure for gamma>=0.20: "
    f"mean="
    f"{large_budget_df['flow_weighted_exposure'].mean():.6f}, "
    f"range=["
    f"{large_budget_df['flow_weighted_exposure'].min():.6f}, "
    f"{large_budget_df['flow_weighted_exposure'].max():.6f}]"
)


print(
    f"For gamma>=0.40: "
    f"SPSE range="
    f"{plateau_df['spse'].max() - plateau_df['spse'].min():.4f}, "
    f"distance range="
    f"{plateau_df['total_distance'].max() - plateau_df['total_distance'].min():.2f} km, "
    f"flow-weighted exposure range="
    f"{plateau_df['flow_weighted_exposure'].max() - plateau_df['flow_weighted_exposure'].min():.6f}"
)


print(
    "Distance below baseline at every positive budget:",
    bool(
        (
            positive_df["total_distance"]
            < baseline_total_distance
        ).all()
    )
)